### ISSUE TITLE
Text conditioning with FiLM layers?

### ISSUE THREAD

**Issue by Olimoyo** [lucidrains/robotic-transformer-pytorch#3]
Hi,

I noticed that the text conditioning is done using classifier-free guidance while in the original paper, they use FiLM layers. 

Was there a particular reason for this decision? 

Thank you,
Oliver

**Comment by lucidrains** [comment]
yea, because i know cross attention on fine-grained tokens is better

**Comment by Olimoyo** [comment]
I see, thanks!
